#+TITLE:MPV
#+STARTUP: nohideblocks

[[https://mpv.io/manual/master/][official manual]], [[https://wiki.archlinux.org/title/mpv][arch mpv page]] (which i used for "getting in"), [[https://mpv.io/manual/master/#keyboard-control][keybindings]]

Download and put [[https://github.com/hl2guide/better-mpv-config][better-mpv-config]] in your mpv config dir (~/.config/mpv in my
case)

Also put [[https://github.com/mpv-player/mpv/blob/master/TOOLS/umpv][umpv]] script in same (not necessarily, but othervise don't forget to
change qt config.py) dir (name it just ~umpv~)

[[https://github.com/stax76/mpv.net][mpv.net]] for windows ?

** Scripts added [[https://github.com/mpv-player/mpv/wiki/User-Scripts][#user-scripts]]
*** [[file:scripts/sponsorblock.lua][sponsorblock]]
A fully-featured port of [SponsorBlock](https://github.com/ajayyy/SponsorBlock) for mpv.

*NOTE*: i've set ~local_database = false~ in script file ([[https://github.com/po5/mpv_sponsorblock/issues/50][gh-issue]])

mp.add_key_binding("Alt+6", "set_segment", set_segment)
mp.add_key_binding("Alt+7", "submit_segment", submit_segment)
mp.add_key_binding("Alt+u", "upvote_segment", function() return vote("1") end)
mp.add_key_binding("Alt+d", "downvote_segment", function() return vote("0") end)

*** TODO [[file:scripts/dbvol.lua][dbvol]] [[https://gist.github.com/Artefact2/0a9c87d6d0f0ef6a565e44d830943fff][#docs]]
volume control using decibels, ~j/k~

starts at -12 db?

*** WAIT [[file:scripts/interSubs.lua][interSubs]] [[https://github.com/oltodosel/interSubs][#docs]]
-- default keybinding to start/stop: F5
-- default keybinding to hide/show: F6
*** TODO mpv-lastfm [[https://github.com/l29ah/w3crapcli/blob/master/last.fm/mpv-lastfm.lua][#docs]]
*** TODO [[file:scripts/blur-edges.lua][blur-edges]] [[https://github.com/occivink/mpv-scripts#blur-edgeslua][#docs]]
kbd at the bottom of the script

*NOTE* slows everything down *a lot* + triggers only on fullscreen toggle

*** [[file:scripts/mpv_chapters.js][mpv-chapters]] [[https://github.com/zxhzxhz/mpv-chapters][#docs]]
Press tab to toggle chapter menu and jump with mouse click
*** IDEA subtitles
either [[https://github.com/directorscut82/find_subtitles][this]] or [[https://github.com/davidde/mpv-autosub][this]]. Former - press to download, latter - automatic
also search on scripts page for 'sub-', there are lots of utility scripts for
working with subtitles

and yet another [[https://github.com/wiiaboo/mpv-scripts/blob/master/subit.lua][script]] for subtitles

**** IDEA when learning jap
[[https://github.com/linguisticmind/mpv-scripts/tree/master/copy-subtitle][copy-subtitle]]
and [[https://github.com/liberlanco/mpv-lang-learner][lang-learner]] as a must
and [[https://github.com/Ben-Kerman/immersive][immersive]] also for learning
[[https://github.com/fxmarty/rikai-mpv][rikay-mpv]] - special for jap
[[https://github.com/laelnasan/yomichampv][yomichampv]]
*** osc-style
Tried [[https://github.com/422658476/MPV-EASY-Player/tree/master/mpv-easy-data/osc-style][this]] source, wasn't able to get anything decent
*** [[file:scripts/quack.lua][quack]] [[https://github.com/CounterPillow/mpv-quack][#docs]]
temporarily reduce the volume after a seek
*** [[file:scripts/reload.lua][reload]] [[https://github.com/4e6/mpv-reload][#docs]]
~ctrl+r~ to reload if anything is wrong / stuck
*** IDEA [[file:scripts/search-page.lua][search-page]] [[https://github.com/CogentRedTester/mpv-search-page][#docs]]
*Rewrite dat shit* as in vim with [[https://mpv.io/manual/master/#javascript][JS]]

Also changed esc for Ctrl+[ in [[file:scripts/user-input.lua][user-input.lua]] and altered lines below in
[[file:script-modules/scroll-list.lua]]

: keybinds = {
    : {'j', 'scroll_down', function() vars:scroll_down() end, {repeatable = true}},
    : {'k', 'scroll_up', function() vars:scroll_up() end, {repeatable = true}},
    : {'Ctrl+[', 'close_browser', function() vars:close() end, {}}
: }


search for keybinds, properties, options and commands and have matching entries display on the OSD.

The default keybinds are listed below, these can be overwritten using input.conf:

f12         script-binding open-search-page
Shift+f12   script-binding open-search-page/advanced
            script-message open-page [page]
            script-message open-page/advanced [page]

The default keybinds are listed below, these can be overwritten using input.conf:

f12         script-binding open-search-page
Shift+f12   script-binding open-search-page/advanced
            script-message open-page [page]
            script-message open-page/advanced [page]

*** [[file:scripts/youtube-search.lua][youtube-search]] [[https://github.com/CogentRedTester/mpv-scripts/raw/master/youtube-search.lua][#source]]
Read script top comment for installation & keybindings (yt api key i've created)

mp.add_key_binding(nil, "yt", open_search_input)
mp.add_key_binding("/", "youtube-search", function()

\+ j/k and C-[

*** [[https://github.com/Eisa01/mpv-scripts#smartcopypaste_ii][smartcopypaste II]], [[https://github.com/Eisa01/mpv-scripts#simplehistory][simplehistory]] and [[https://github.com/Eisa01/mpv-scripts#undoredo][undoredo]]
**** *smartcopypaste ii* default keybinds:
- C-c :: copy vid url
- C-v :: paste vid url
- C-C :: copy vid url with timestamp
- C-V :: paste as a playlist
- M-c :: open copypaste list with filters (a[ll], r[ecents], f[ileonly],
  d[istinct], k[eywords], more 'bout filters again in =conf= file)

Keybindings that will be used to navigate up on the list:

k/j, C-b/f, g[g]/G, C-[, / as in vim

#--Keybind that will be used to load highlighted entry from the list
list_select_keybind=["ENTER"]
#--Keybind that will be used to add the selected entry to playlist
list_add_playlist_keybind=["SHIFT+ENTER"]
#--Keybind that will be used to close the list (closes search first if it is open)
list_close_keybind=["ESC", "q", "ctrl+["]
#--Keybind that will be used to delete the highlighted entry from the list
list_delete_keybind=["DEL"]
#--Keybind that will be used to exit typing mode of search while keeping search open
list_search_not_typing_mode_keybind=["CTRL+ENTER"]
#--Keybind thats are ignored when list is open
list_ignored_keybind=["h", "H", "r", "R", "b", "B", "k", "K"]

**** *simplehistory* Default Keybinds:
Ctrl+r resume in any previously closed videos / idle: loads and resumes last played video
Alt+r add last closed video into playlist / idle: loads last closed video without resuming
h opens History list (Log Manager)
r opens History list - filtered with recent items (Log Manager)

history_resume_keybind=["Alt+>"]
history_load_last_keybind=["alt+<"]
open_list_keybind=[ ["Alt+h"] ]
list_filter_jump_keybind=[ ["a", "all"], ["r", "recents"], ["d", "distinct"], ["f", "fileonly"] ]
history_incognito_mode_keybind=["Alt+H"]
next_filter_sequence_keybind=["l"]
previous_filter_sequence_keybind=["h"]
list_cycle_sort_keybind=["o"]

*Vim*: hjkl, C-b/f, g/G, /
list_highlight_move_keybind=["SHIFT"]
list_highlight_all_keybind=["h"]
list_unhighlight_all_keybind=["H"]
#--Keybind that will be used to add entry to playlist based on cursor position
list_add_playlist_keybind=["CTRL+ENTER"]
#--Keybind that will be used to add all highlighted entries to playlist
list_add_playlist_highlighted_keybind=["SHIFT+ENTER"]
list_close_keybind=["ESC", "q", "Ctrl+["]
list_delete_keybind=["d"]
list_delete_highlighted_keybind=["D"]
#--Keybind that will be used to exit typing mode of search while keeping search open
list_search_not_typing_mode_keybind=["ALT+ENTER"]
#--Keybind thats are ignored when list is open
list_ignored_keybind=["B", "b", "K", "c", "C"]

**** *undoredo* Default Keybinds
mp.add_key_binding("u", "undo", undo)
mp.add_key_binding("r", "redo", redo)
mp.add_key_binding("U", "undoLoop", undoLoop)

*** [[file:scripts/youtube-quality.lua][youtube-quality]] [[https://github.com/jgreco/mpv-youtube-quality][#docs]]
Change youtube video quality on the fly.

toggle_menu_binding=alt+q
k,j

*** [[file:scripts/youtube-upnext.lua][youtube-upnext]] [[https://github.com/cvzi/mpv-youtube-upnext][#docs]]
Fetch upnext/recommended videos from youtube

toggle_menu_binding=alt+.
k,j

*** [?] [[https://github.com/occivink/mpv-gallery-view/][mpv-gallery-view]]
*Playlist-view*:
- ~G~ to toggle gallery view
- hjkl, C-b/f, g/G, C-[, D[elete]
- TAB - flag

*Contact-sheet*:
- ~C~ to toggle contact view (changed not in .conf tho, there is no option)
- mouse_support=no
- hjkl, C-b/f, g/G, C-[

** Todo
*** TODO [[https://github.com/sebaro/ViewTube][viewtube]] for my main pc?
*** HOLD mpv as a music player
[[https://wiki.archlinux.org/title/mpv][this]] article also has a section called /Improving mpv as a music player with Lua
scripts/ which might b sometime useful again for my main pc
*** IDEA [[https://github.com/zenyd/mpv-scripts][copy-paste-url]]
*** IDEA Anime
https://github.com/ehoneyse/mpv-open-anilist-page
** To keep in mind
*** [[https://github.com/cvzi/mpv-youtube-download][mpv-youtube-download]]
*** [[https://gist.github.com/bitingsock/17d90e3deeb35b5f75e55adb19098f58][ytdl-preload]]
** Keybindings
:PROPERTIES:
:header-args: :tangle input.conf
:END:

[[https://github.com/mpv-player/mpv/blob/master/etc/input.conf][default keybindings]]

Use SHARP to assign the # key.

List of commands and further details: DOCS/man/input.rst
List of special keys: --input-keylist
Keybindings testing mode: mpv --input-test --force-window --idle

Use 'ignore' to unbind a key fully (e.g. 'ctrl+a ignore').

Strings need to be quoted and escaped:
  KEY show-text "This is a single backslash: \\ and a quote: \" !"

The default keybindings are hardcoded into the mpv binary.
You can disable them completely with: --no-input-default-bindings

Developer note:
On compilation, this file is baked into the mpv binary, and all lines are
uncommented (unless '#' is followed by a space) - thus this file defines the
default key bindings.

If this is enabled, treat all the following bindings as default:
#+begin_src conf
# DO NOT ALTER THIS FILE DIRECTLY, IT'S BEING TANGLED FROM README

default-bindings start
#+end_src

*** Playback
#+begin_src conf
# Seek units are in seconds, but note that these are limited by keyframes
l seek  10                          # seek 5 seconds forward
h seek -10                          # seek 5 seconds backward
# Do smaller, always exact (non-keyframe-limited), seeks with shift.
# Don't show them on the OSD (no-osd).
# Shift+UP    no-osd seek  5 exact       # seek exactly 5 seconds forward
# Shift+DOWN  no-osd seek -5 exact       # seek exactly 5 seconds backward
Ctrl+LEFT   no-osd sub-seek -1         # seek to the previous subtitle
Ctrl+RIGHT  no-osd sub-seek  1         # seek to the next subtitle
Alt++     add video-zoom   0.1         # zoom in
Alt+-     add video-zoom  -0.1         # zoom out
PGUP add chapter 1                     # seek to the next chapter
PGDWN add chapter -1                   # seek to the previous chapter

[ multiply speed 1/1.1                 # decrease the playback speed
] multiply speed 1.1                   # increase the playback speed
{ multiply speed 0.5                   # halve the playback speed
} multiply speed 2.0                   # double the playback speed
0 set speed 1.0                       # reset the speed to normal

. frame-step                           # advance one frame and pause
, frame-back-step                      # go back by one frame and pause

SPACE cycle pause                      # toggle pause/playback mode

PLAY cycle pause                       # toggle pause/playback mode
PAUSE cycle pause                      # toggle pause/playback mode
PLAYPAUSE cycle pause                  # toggle pause/playback mode
PLAYONLY set pause no                  # unpause
PAUSEONLY set pause yes                # pause
FORWARD seek 60                        # seek 1 minute forward
REWIND seek -60                        # seek 1 minute backward
#+end_src
*** [?] Subtitles
TEST ~Alt+Ctrl+C~

#+begin_src conf
Alt+Ctrl+- add sub-delay -0.1                   # shift subtitles 100 ms earlier
Alt+Ctrl++ add sub-delay +0.1                   # delay subtitles by 100 ms

Alt+c cycle sub-visibility                 # hide or show the subtitles
Alt+C cycle sub-ass-vsfilter-aspect-compat # toggle stretching SSA/ASS subtitles with anamorphic videos to match the historical renderer
Alt+Ctrl+C cycle-values sub-ass-override "force" "no" # toggle overriding SSA/ASS subtitle styles with the normal styles
Alt+Ctrl+c cycle sub                            # switch subtitle track
#+end_src

Bind those if ya'll ever need 'em:
Shift+g add sub-scale +0.1             # increase the subtitle font size
Shift+f add sub-scale -0.1             # decrease the subtitle font size
Ctrl+Shift+LEFT sub-step -1            # change subtitle timing such that the previous subtitle is displayed
Ctrl+Shift+RIGHT sub-step 1            # change subtitle timing such that the next subtitle is displayed

*** Audio
#+begin_src conf
ctrl++ add audio-delay 0.100           # change audio/video sync by delaying the audio
ctrl+- add audio-delay -0.100          # change audio/video sync by shifting the audio earlier
j add volume -2
k add volume 2
m cycle mute                           # toggle mute
#+end_src

*** Filters
#+begin_src conf
Alt+1 add contrast -1
Alt+2 add contrast 1
Alt+3 add brightness -1
Alt+4 add brightness 1
Alt+5 add gamma -1
Alt+6 add gamma 1
Alt+7 add saturation -1
Alt+8 add saturation 1
#+end_src

*** Misc
#+begin_src conf
# Quitting
# q quit
Q quit-watch-later                     # exit and remember the playback position
# q {encode} quit 4
ESC set fullscreen no                  # leave fullscreen
ESC {encode} quit 4

Alt+0 set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0 # reset zoom and pan settings
? show-progress                        # show playback progress
i script-binding stats/display-stats-toggle # toggle displaying information and statistics
` script-binding console/enable        # open the console
Ctrl+F cycle fullscreen                     # toggle fullscreen

Alt+a cycle audio                      # switch audio track
Alt+v cycle video                          # switch video track
Alt+Ctrl+v cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1" # cycle the video aspect ratio ("-1" is the container aspect)

> playlist-next                        # skip to the next file
< playlist-prev                        # skip to the previous file

Ctrl+S screenshot video                     # take a screenshot of the video in its original resolution without subtitles

Alt+l ab-loop                              # set/clear A-B loop points
Alt+L cycle-values loop-file "inf" "no"    # toggle infinite looping

& show-text ${playlist}               # show the playlist
^ show-text ${track-list}             # show the list of video, audio and sub tracks
#+end_src

*** Unknown purpose
#w add panscan -0.1                     # decrease panscan
#W add panscan +0.1                     # shrink black bars by cropping the video
#e add panscan +0.1                     # shrink black bars by cropping the video

#E cycle edition                        # switch edition
#ctrl+h cycle-values hwdec "auto" "no"  # toggle hardware decoding

#d cycle deinterlace                    # toggle the deinterlacing filter
*** TODO Known free
C, *
