#+TITLE:MPV
#+STARTUP: nohideblocks

[[https://mpv.io/manual/master/][official manual]], [[https://wiki.archlinux.org/title/mpv][arch mpv page]] (which i deem to b a _must-read_)

*Dependencies*: libsixel, lua52, sndio

** Configuration
*** mpv.conf
:PROPERTIES:
:header-args: :tangle mpv.conf
:END:

External Sources of this config:
- https://wiki.archlinux.org/title/mpv    <-- READ WHOLE
- https://github.com/hl2guide/better-mpv-config
- https://raw.githubusercontent.com/classicjazz/mpv-config/master/mpv.conf

#+begin_src conf
# DO NOT ALTER! This config is tangled from README

# ===== Seeking =====
save-position-on-quit=yes               # saves the seekbar position on exit
force-seekable=yes                      # forces videos to be seekable

# ===== RAM =====
cache=yes                               # uses a large seekable RAM cache even for local input.
# cache-secs=300                        # uses extra large RAM cache (needs cache=yes to make it useful).
demuxer-max-back-bytes=20M              # sets fast seeking
demuxer-max-bytes=20M                   # sets fast seeking
# demuxer-max-bytes=1800M
# demuxer-max-back-bytes=1200M

# ===== Video =====
vlang=en,eng                            # Sets the video language
# https://github.com/mpv-player/mpv/wiki/GPU-Next-vs-GPU
vo=gpu-next                             # Sets the video out to an experimental video renderer based on libplacebo
# vo=gpu         # Uses GPU-accelerated video output by default.
# profile=gpu-hq # Can cause performance problems with some GPU drivers and GPUs.

# ===== General =====
hls-bitrate=max                         # uses max quality for HLS streams
pause=yes                               # disables autoplay
prefetch-playlist=yes                   # prefetches the playlist

# --- other settings ---

# TESTING - AMD and Intel
# hwdec=vaapi     # 'nvdec' if using Nvidia gpu
hwdec=auto # enable best HW decoder; turn off for software decoding

border=no              # hides the window title bar

# Sets the profile restore method to "copy if equal"
profile-restore=copy-equal
#+end_src

**** Audio
#+begin_src conf
volume-max=100                          # maximum volume in %, everything above 100 results in amplification
volume=70                               # default volume, 100 = unchanged

# af-add='dynaudnorm=g=5:f=250:r=0.9:p=0.5' # Normalizes audio
# af=scaletempo2
#+end_src

**** Motion interpolation
Enabling those will significantly drop performance on my machine

#+begin_src conf
override-display-fps=60
video-sync=display-resample
interpolation=yes
tscale=oversample # smoothmotion
#+end_src

**** Color Space
#+begin_src conf
# see https://github.com/mpv-player/mpv/wiki/Video-output---shader-stage-diagram
target-prim=auto
# target-prim=bt.709 # target Rec.709 for SDR TVs
# target-prim=bt.2020 # target Rec.2020 (wide color gamut) for HDR TVs
target-trc=auto
gamma-auto
vf=format=colorlevels=full:colormatrix=auto
video-output-levels=full
#+end_src

**** Dithering
#+begin_src conf
dither-depth=auto
temporal-dither=yes
dither=fruit
#+end_src

**** Debanding
Debanding is a video processing technique that helps reduce visual artifacts
caused by banding. Banding refers to the visible striping or posterization that
might occur in areas of smooth gradients, where subtle color or tonal
transitions appear as distinct bands rather than a smooth gradient. Debanding
algorithms smooth out these abrupt transitions, resulting in a more visually
pleasing and natural-looking video. In the context of mpv, debanding is a
feature that can be applied during video playback to enhance the visual quality.

#+begin_src conf
deband=yes          # enabled by default
deband-iterations=4 # deband steps
deband-threshold=48 # deband strength
deband-range=16     # deband range
deband-grain=48     # dynamic grain: set to "0" if using the static grain shader
#+end_src

**** Subtitles
#+begin_src conf
blend-subtitles=yes
sub-auto=fuzzy # Enable fuzzy searching:
#+end_src
**** User scripts
***** UOSC
#+begin_src conf
# required so that the 2 UIs don't fight each other
osc=no
# uosc provides its own seeking/volume indicators, so you also don't need this
osd-bar=no
# uosc will draw its own window controls if you disable window border
border=no

# uosc respects this setting
# osd-font='Iosevka'

# And these doesn't
# osd-font-size=45
# osd-scale=0.5
#+end_src

**** My customs
#+begin_src conf
no-input-builtin-bindings
#+end_src
**** Custom profiles ( must be last )
#+begin_src conf
[fastforward]
profile-restore=copy-equal
# scale=bilinear
# dscale=bilinear
# cscale=bilinear
vd-lavc-skiploopfilter=all
vd-lavc-skipframe=all
#+end_src

***** File Type Profiles
#+begin_src conf
# GIF Files
[extension.gif]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=gif
cache=no
no-pause
loop-file=yes
# WebM Files
[extension.webm]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=webm
no-pause
loop-file=yes
#+end_src
***** Protocol Specific Configuration
#+begin_src conf
[protocol.http]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=http
hls-bitrate=max # use max quality for HLS streams
cache=yes
no-cache-pause # don't pause when the cache runs low

[protocol.https]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=https
profile=protocol.http

[protocol.ytdl]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=ytdl
profile=protocol.http
#+end_src

**** Inactive /mpv.conf/ settings
:PROPERTIES:
:header-args: :tangle no
:END:

***** Upscaling & Processing
#+begin_src conf
# glsl-shaders-clr # luma upscaling
# note: any FSRCNNX above FSRCNNX_x2_8-0-4-1 is not worth the additional computional overhead
# glsl-shaders="~/.config/mpv/shaders/FSRCNNX_x2_8-0-4-1.glsl"
# scale=ewa_lanczos # luma downscaling
# note: ssimdownscaler is tuned for mitchell and downscaling=no
# glsl-shaders-append="~/.config/mpv/shaders/SSimDownscaler.glsl"
# dscale=mitchell
# linear-downscaling=no # chroma upscaling and downscaling
# glsl-shaders-append="~/.config/mpv/shaders/KrigBilateral.glsl"
# cscale=mitchell
# sigmoid-upscaling=yes
#+end_src

*** input.conf
:PROPERTIES:
:header-args: :tangle input.conf
:END:

[[file:/usr/share/doc/mpv/input.conf][default keybindings]]

Use SHARP to assign the ~#~ key.

- List of commands and further details: DOCS/man/input.rst
- List of special keys: --input-keylist
- Keybindings testing mode: mpv --input-test --force-window --idle

Use 'ignore' to unbind a key fully (e.g. 'ctrl+a ignore').

Strings need to be quoted and escaped:
  KEY show-text "This is a single backslash: \\ and a quote: \" !"

#+begin_src conf
# THIS FILE IS BEING TANGLES FROM README

# If this is enabled, treat all the following bindings as default:
default-bindings start
#+end_src

*Note:* All key bindings below that are bound to ~_~ are defined as leader ones in
my leader script.

**** Playback
#+begin_src conf
# Seek units are in seconds, but note that these are limited by keyframes
l seek  5                          # seek 5 seconds forward
h seek -5                          # seek 5 seconds backward
RIGHT seek  5                          # seek 5 seconds forward
LEFT  seek -5                          # seek 5 seconds backward
# Do smaller, always exact (non-keyframe-limited), seeks with shift.
# Don't show them on the OSD (no-osd).
L no-osd seek  10 exact       # seek exactly 10 seconds forward
H no-osd seek -10 exact       # seek exactly 10 seconds backward

[ multiply speed 1/1.1 # decrease the playback speed
] multiply speed 1.1   # increase the playback speed
> multiply speed 2.0   # double the playback speed
< multiply speed 0.5   # halve the playback speed
0 set speed 1.0        # reset the speed to normal

SPACE cycle pause       # toggle pause/playback mode
PLAY cycle pause        # toggle pause/playback mode
PAUSE cycle pause       # toggle pause/playback mode
PLAYPAUSE cycle pause   # toggle pause/playback mode
PLAYONLY set pause no   # unpause
PAUSEONLY set pause yes # pause
#+end_src

**** Audio
#+begin_src conf
j add volume -2
k add volume 2
m cycle mute                           # toggle mute
#+end_src

**** Misc
#+begin_src conf
# Quitting
# q quit
Q quit-watch-later # exit and remember the playback position
# q {encode} quit 4
ESC set fullscreen no                  # leave fullscreen
ESC {encode} quit 4

# toggle displaying information and statistics (https://mpv.io/manual/master/#stats)
i script-binding stats/display-stats-toggle 
` script-binding console/enable        # open the console
Ctrl+F cycle fullscreen                     # toggle fullscreen

Alt+v cycle video                          # switch video track
# cycle the video aspect ratio ("-1" is the container aspect)
Alt+Ctrl+v cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"

# take a screenshot of the video in its original resolution without subtitles
Ctrl+S screenshot video
#+end_src

** [[https://github.com/stax76/awesome-mpv][User scripts]]
*** my [[https://github.com/Seme4eg/mpv-scripts][own]] scripts
#+begin_src bash :tangle sources
get M-x-rofi script https://raw.githubusercontent.com/Seme4eg/mpv-scripts/master/M-x-rofi.lua
get M-x-rofi options https://raw.githubusercontent.com/Seme4eg/mpv-scripts/master/script-opts/M_x_rofi.conf

get leader script https://raw.githubusercontent.com/Seme4eg/mpv-scripts/master/leader.lua
get leader module https://raw.githubusercontent.com/Seme4eg/mpv-scripts/master/script-modules/leader.lua
get leader options https://raw.githubusercontent.com/Seme4eg/mpv-scripts/master/script-opts/leader.conf
#+end_src

*** [[https://gist.github.com/Artefact2/0a9c87d6d0f0ef6a565e44d830943fff][dbvol]] - volume control using decibels
#+begin_src bash :tangle sources
get dbvol script https://gist.githubusercontent.com/Artefact2/0a9c87d6d0f0ef6a565e44d830943fff/raw/c841063304a98f99371ce28e0b14ade609e8185c/dbvol.lua
#+end_src

#+begin_src conf :tangle input.conf :comments noweb
j script-binding dbvol/decrease-db
k script-binding dbvol/increase-db
#+end_src

*** [[https://github.com/occivink/mpv-scripts#blur-edgeslua][blur-edges]]
Fills the black bars on the side of a video with a blurred copy of its edges.

*NOTE* slows everything down *a lot* + triggers only on fullscreen toggle

#+begin_src bash :tangle sources
get blur_edges script https://raw.githubusercontent.com/occivink/mpv-scripts/master/scripts/blur-edges.lua
get blur_edges options https://raw.githubusercontent.com/occivink/mpv-scripts/master/script-opts/blur_edges.conf
#+end_src

#+begin_src conf :tangle input.conf :comments link
Alt+b script-binding blur-edges/toggle-blur
#+end_src

*** [[https://github.com/CounterPillow/mpv-quack][quack]] temporarily reduce the volume after a seek
#+begin_src bash :tangle sources
get quack script https://raw.githubusercontent.com/CounterPillow/mpv-quack/master/quack.lua
conf_file=quack.conf
! config_exists quack && echo "ducksecs=1" >"$conf_file"
#+end_src
*** [[https://github.com/4e6/mpv-reload][reload]]
~ctrl+r~ to reload if anything is wrong / stuck

#+begin_src bash :tangle sources
get reload script https://raw.githubusercontent.com/sibwaf/mpv-scripts/master/reload.lua
#+end_src

#+begin_src conf :tangle input.conf :comments link
Ctrl+r script-binding reload/reload
#+end_src

*** [[https://github.com/Eisa01/mpv-scripts#undoredo][undoredo]]
#+begin_src bash :tangle sources
get undoredo script https://raw.githubusercontent.com/Eisa01/mpv-scripts/master/scripts/UndoRedo.lua
#+end_src

#+begin_src conf :tangle input.conf :comments link
u script-binding UndoRedo/undo
r script-binding UndoRedo/redo
U script-binding UndoRedo/undoLoop
#+end_src

*** [[https://github.com/AN3223/dotfiles/blob/master/.config/mpv/scripts/lilskippa.lua][lilskippa]] fast forward to scene/black/silence
-- This script defines the following keybinds:
--
-- % skip2scene   -- skip2scene fast forwards to the next scene change
-- ^ skip2black   -- skip2black fast forwards to the next black video segment
-- & skip2silence -- skip2silence fast forwards to the next silent audio segment

#+begin_src bash :tangle sources
get lilskippa script https://raw.githubusercontent.com/AN3223/dotfiles/master/.config/mpv/scripts/lilskippa.lua
#+end_src

#+begin_src conf :tangle input.conf :comments link

#+end_src

*** [[https://github.com/l-jared/thumbfast][thumbfast]] High-performance on-the-fly thumbnailer for mpv.
#+begin_src bash :tangle sources
get thumbfast script https://raw.githubusercontent.com/l-jared/thumbfast/master/thumbfast.lua
get thumbfast options https://raw.githubusercontent.com/l-jared/thumbfast/master/thumbfast.conf
#+end_src

*** TODO [[https://github.com/tomasklaen/uosc][uosc]] Feature-rich minimalist proximity-based UI for MPV player.
#+begin_src bash :tangle sources
get_uosc() {
    config_dir="${XDG_CONFIG_HOME:-~/.config}"
    mkdir -pv "$config_dir"/mpv/script-opts/
    rm -rf "$config_dir"/mpv/scripts/uosc_shared
    wget -P /tmp/ https://github.com/tomasklaen/uosc/releases/latest/download/uosc.zip
    unzip -od "$config_dir"/mpv/ /tmp/uosc.zip
    rm -fv /tmp/uosc.zip
    get uosc options https://github.com/tomasklaen/uosc/releases/latest/download/uosc.conf
}

if [ $command == sync ]; then
    [ ! -f ./scripts/uosc.lua ] && get_uosc
else
    get_uosc
fi
#+end_src

** To do list [1/9]
*** DONE [#B] migrate from 'extended-menu' to external rofi
use [[https://codeberg.org/NRK/mpv-toolbox/src/branch/master/mdmenu/mdmenu.lua][mdmenu]] and [[https://git.smrk.net/mpv-scripts/file/history.lua.html][history.lua]] scripts as examples

*** TODO [#B] recents
take any script that SIMPLY logs history and pipe it to rofi

[[https://gist.github.com/garoto/e0eb539b210ee077c980e01fb2daef4a][script 1]], [[https://github.com/hacel/recent][script 2]]

Example of line format in history.log file (see how it forms [[https://github.com/Eisa01/mpv-scripts#simplehistory][here]]):
: [Wednesday/September 06/09/2023 19:17:52] "output.lq.mp4" | https://dl4.vibio.tv/f064277c672d45c35a49426dca2020f7/2839/2839278/output.lq.mp4 | length=5367.4472335601 | time=5367.4100453432

*** IDEA [#B] [[https://github.com/noctuid/mpv-webtorrent-hook][mpv-webtorrent-hook]]
several deps, view installation section in docs
*** IDEA [[https://github.com/zenyd/mpv-scripts][copy-paste-url]]
*** IDEA [[https://gist.github.com/myfreeer/d744c445aa71c0eeb165ca39cf6c0511][cycle-denoise]]
*** IDEA [[https://github.com/ferreum/mpv-skipsilence][mpv-skipsilence]] and [[https://github.com/detuur/mpv-scripts/blob/master/skiptosilence.lua][skiptosilence]]
*** IDEA Anime
https://github.com/ehoneyse/mpv-open-anilist-page
*** IDEA Shaders
Check [[https://github.com/hl2guide/better-mpv-config/blob/master/mpv_v3/configs/mpv_shaders.conf][these]] config settings and shaders [[https://github.com/hl2guide/better-mpv-config/tree/master/mpv_v3/shaders][dir]] in same repo.

[[https://github.com/AN3223/dotfiles/blob/master/.config/mpv/scripts/pickshader.lua][pickshader]] script

[[https://github.com/mpv-player/mpv/wiki/User-Scripts#user-shaders][#user-shaders]] ([[https://github.com/bloc97/Anime4K/blob/master/GLSL_Instructions.md][Anime4K]])

*** IDEA subtitles
- Check [[https://github.com/hl2guide/better-mpv-config/blob/master/mpv_v3/configs/mpv_subtitles.conf][these]] config settings for subtitles.
- check [[https://github.com/stax76/awesome-mpv#subtitle][this]] user-script list

either [[https://github.com/directorscut82/find_subtitles][this]] or [[https://github.com/davidde/mpv-autosub][this]]. Former - press to download, latter - automatic
also search on scripts page for 'sub-', there are lots of utility scripts for
working with subtitles

and yet another [[https://github.com/wiiaboo/mpv-scripts/blob/master/subit.lua][script]] for subtitles

Bind those if ya'll ever need 'em:
- Shift+g add sub-scale +0.1             # increase the subtitle font size
- Shift+f add sub-scale -0.1             # decrease the subtitle font size
- Ctrl+Shift+LEFT sub-step -1            # change subtitle timing such that the previous subtitle is displayed
- Ctrl+Shift+RIGHT sub-step 1            # change subtitle timing such that the next subtitle is displayed

**** IDEA when learning jap
[[https://github.com/linguisticmind/mpv-scripts/tree/master/copy-subtitle][copy-subtitle]]
and [[https://github.com/liberlanco/mpv-lang-learner][lang-learner]] as a must
and [[https://github.com/Ben-Kerman/immersive][immersive]] also for learning
[[https://github.com/fxmarty/rikai-mpv][rikay-mpv]] - special for jap
[[https://github.com/laelnasan/yomichampv][yomichampv]]
