#+TITLE:MPV
#+STARTUP: nohideblocks

[[https://mpv.io/manual/master/][official manual]], [[https://wiki.archlinux.org/title/mpv][arch mpv page]] (which i deem to b a *must-read*)

** Contents :TOC_3:noexport:
  - [[#compilation][Compilation]]
  - [[#scripts-added-user-scripts][Scripts added #user-scripts]]
    - [[#sponsorblock][sponsorblock]]
    - [[#dbvol-docs][dbvol #docs]]
    - [[#wait-intersubs-docs][WAIT interSubs #docs]]
    - [[#mpv-lastfm-docs][mpv-lastfm #docs]]
    - [[#blur-edges-docs][blur-edges #docs]]
    - [[#idea-subtitles][IDEA subtitles]]
    - [[#quack-docs][quack #docs]]
    - [[#reload-docs][reload #docs]]
    - [[#mpv-webtorrent-hook][mpv-webtorrent-hook]]
    - [[#youtube-search-source][youtube-search #source]]
    - [[#smartcopypaste-ii-simplehistory-and-undoredo][smartcopypaste II, simplehistory and undoredo]]
    - [[#youtube-quality-docs][youtube-quality #docs]]
    - [[#youtube-upnext-docs][youtube-upnext #docs]]
    - [[#ytdlautoformat-docs][ytdlautoformat #docs]]
    - [[#mpv-gallery-view][mpv-gallery-view]]
    - [[#scripts-to-keep-in-mind][Scripts to keep in mind]]
  - [[#shaders-added-user-shaders][Shaders added #user-shaders]]
    - [[#anime4k][Anime4K]]
  - [[#configuration][Configuration]]
    - [[#mpvconf][mpv.conf]]
    - [[#inputconf][input.conf]]
  - [[#to-do-list-05][To do list]]
    - [[#viewtube-for-my-main-pc][viewtube for my main pc?]]
    - [[#mpvnet-for-windows-][mpv.net for windows ?]]
    - [[#hold-mpv-as-a-music-player][HOLD mpv as a music player]]
    - [[#idea-copy-paste-url][IDEA copy-paste-url]]
    - [[#idea-anime][IDEA Anime]]

** Compilation
*Dependencies*:
- =mujs= - for js scripts (i ain't usin any js scripts for now)
- =vapoursynth= - for python scripts
- =luajit= - lua Just In Time compilation so the meson script can see those deps
  and add needed build flags before building.

Now proceed to [[https://github.com/mpv-player/mpv/#compilation][compilation]] section.

** Scripts added [[https://github.com/mpv-player/mpv/wiki/User-Scripts][#user-scripts]]
*** [[file:scripts/sponsorblock.lua][sponsorblock]]
A fully-featured port of [SponsorBlock](https://github.com/ajayyy/SponsorBlock) for mpv.

*NOTE*: i've set ~local_database = false~ in script file ([[https://github.com/po5/mpv_sponsorblock/issues/50][gh-issue]])

#+begin_src lua
mp.add_key_binding("Alt+6", "set_segment", set_segment)
mp.add_key_binding("Alt+7", "submit_segment", submit_segment)
mp.add_key_binding("Alt+u", "upvote_segment", function() return vote("1") end)
mp.add_key_binding("Alt+d", "downvote_segment", function() return vote("0") end)
#+end_src

*** [[file:scripts/dbvol.lua][dbvol]] [[https://gist.github.com/Artefact2/0a9c87d6d0f0ef6a565e44d830943fff][#docs]]
volume control using decibels, ~j/k~

*** WAIT [[file:scripts/interSubs.lua][interSubs]] [[https://github.com/oltodosel/interSubs][#docs]]
- default keybinding to start/stop: F5
- default keybinding to hide/show: F6
*** TODO mpv-lastfm [[https://github.com/l29ah/w3crapcli/blob/master/last.fm/mpv-lastfm.lua][#docs]]
*** TODO [[file:scripts/blur-edges.lua][blur-edges]] [[https://github.com/occivink/mpv-scripts#blur-edgeslua][#docs]]
kbd at the bottom of the script

*NOTE* slows everything down *a lot* + triggers only on fullscreen toggle

*** IDEA subtitles
either [[https://github.com/directorscut82/find_subtitles][this]] or [[https://github.com/davidde/mpv-autosub][this]]. Former - press to download, latter - automatic
also search on scripts page for 'sub-', there are lots of utility scripts for
working with subtitles

and yet another [[https://github.com/wiiaboo/mpv-scripts/blob/master/subit.lua][script]] for subtitles

**** IDEA when learning jap
[[https://github.com/linguisticmind/mpv-scripts/tree/master/copy-subtitle][copy-subtitle]]
and [[https://github.com/liberlanco/mpv-lang-learner][lang-learner]] as a must
and [[https://github.com/Ben-Kerman/immersive][immersive]] also for learning
[[https://github.com/fxmarty/rikai-mpv][rikay-mpv]] - special for jap
[[https://github.com/laelnasan/yomichampv][yomichampv]]
*** [[file:scripts/quack.lua][quack]] [[https://github.com/CounterPillow/mpv-quack][#docs]]
temporarily reduce the volume after a seek
*** [[file:scripts/reload.lua][reload]] [[https://github.com/4e6/mpv-reload][#docs]]
~ctrl+r~ to reload if anything is wrong / stuck
*** [[https://github.com/noctuid/mpv-webtorrent-hook][mpv-webtorrent-hook]]
several deps, view installation section in docs
*** [[file:scripts/youtube-search.lua][youtube-search]] [[https://github.com/CogentRedTester/mpv-scripts/raw/master/youtube-search.lua][#source]]
Read script top comment for installation & keybindings (yt api key i've created)

- mp.add_key_binding(nil, "yt", open_search_input)
- mp.add_key_binding("/", "youtube-search", function()

\+ j/k and C-[

*** [[https://github.com/Eisa01/mpv-scripts#smartcopypaste_ii][smartcopypaste II]], [[https://github.com/Eisa01/mpv-scripts#simplehistory][simplehistory]] and [[https://github.com/Eisa01/mpv-scripts#undoredo][undoredo]]
**** *smartcopypaste ii* default keybinds:
- C-c :: copy vid url
- C-v :: paste vid url
- C-C :: copy vid url with timestamp
- C-V :: paste as a playlist
- M-c :: open copypaste list with filters (a[ll], r[ecents], f[ileonly],
  d[istinct], k[eywords], more 'bout filters again in =conf= file)

Keybindings that will be used to navigate up on the list:

k/j, C-b/f, g[g]/G, C-[, / as in vim

#+begin_src conf
#--Keybind that will be used to load highlighted entry from the list
list_select_keybind=["ENTER"]
#--Keybind that will be used to add the selected entry to playlist
list_add_playlist_keybind=["SHIFT+ENTER"]
#--Keybind that will be used to close the list (closes search first if it is open)
list_close_keybind=["ESC", "q", "ctrl+["]
#--Keybind that will be used to delete the highlighted entry from the list
list_delete_keybind=["DEL"]
#--Keybind that will be used to exit typing mode of search while keeping search open
list_search_not_typing_mode_keybind=["CTRL+ENTER"]
#--Keybind thats are ignored when list is open
list_ignored_keybind=["h", "H", "r", "R", "b", "B", "k", "K"]
#+end_src

**** *simplehistory* Default Keybinds:
- Ctrl+r resume in any previously closed videos / idle: loads and resumes last
  played video
- Alt+r add last closed video into playlist / idle: loads last closed video
  without resuming
- h opens History list (Log Manager)
- r opens History list - filtered with recent items (Log Manager)

#+begin_src conf
history_resume_keybind=["Alt+>"]
history_load_last_keybind=["alt+<"]
open_list_keybind=[ ["Alt+h"] ]
list_filter_jump_keybind=[ ["a", "all"], ["r", "recents"], ["d", "distinct"], ["f", "fileonly"] ]
history_incognito_mode_keybind=["Alt+H"]
next_filter_sequence_keybind=["l"]
previous_filter_sequence_keybind=["h"]
list_cycle_sort_keybind=["o"]
#+end_src

*Vim*: hjkl, C-b/f, g/G, /

#+begin_src conf
list_highlight_move_keybind=["SHIFT"]
list_highlight_all_keybind=["h"]
list_unhighlight_all_keybind=["H"]
#--Keybind that will be used to add entry to playlist based on cursor position
list_add_playlist_keybind=["CTRL+ENTER"]
#--Keybind that will be used to add all highlighted entries to playlist
list_add_playlist_highlighted_keybind=["SHIFT+ENTER"]
list_close_keybind=["ESC", "q", "Ctrl+["]
list_delete_keybind=["d"]
list_delete_highlighted_keybind=["D"]
#--Keybind that will be used to exit typing mode of search while keeping search open
list_search_not_typing_mode_keybind=["ALT+ENTER"]
#--Keybind thats are ignored when list is open
list_ignored_keybind=["B", "b", "K", "c", "C"]
#+end_src

**** *undoredo* Default Keybinds
- mp.add_key_binding("u", "undo", undo)
- mp.add_key_binding("r", "redo", redo)
- mp.add_key_binding("U", "undoLoop", undoLoop)

*** [[file:scripts/youtube-quality.lua][youtube-quality]] [[https://github.com/jgreco/mpv-youtube-quality][#docs]]
Change youtube video quality on the fly.

toggle_menu_binding=alt+q

k,j

*** [[file:scripts/youtube-upnext.lua][youtube-upnext]] [[https://github.com/cvzi/mpv-youtube-upnext][#docs]]
Fetch upnext/recommended videos from youtube

toggle_menu_binding=alt+.

k,j

*** [[file:scripts/ytdlautoformat.lua][ytdlautoformat]] [[https://github.com/Samillion/mpv-ytdlautoformat][#docs]]
A simple mpv script to automatically change ytdl-format (for yt-dlp, youtube-dl)
specifically if the URL is Youtube or Twitch.

/Changd lines:/
#+begin_src lua
local changedQuality = 1080
local enableVP9 = true
local FPSLimit = 60
#+end_src

*** [[https://github.com/occivink/mpv-gallery-view/][mpv-gallery-view]]
*Playlist-view*:
- ~G~ to toggle gallery view
- hjkl, C-b/f, g/G, C-[, D[elete]
- TAB - flag

*Contact-sheet*:
- ~C~ to toggle contact view (changed not in .conf tho, there is no option)
- mouse_support=no
- hjkl, C-b/f, g/G, C-[

*** Scripts to keep in mind
**** [[https://github.com/cvzi/mpv-youtube-download][mpv-youtube-download]]
**** [[https://gist.github.com/bitingsock/17d90e3deeb35b5f75e55adb19098f58][ytdl-preload]]
**** [[https://github.com/Guldoman/mpv_inhibit_gnome][inhibit_gnome]]
prevents screen blanking in GNOME while playing media.
** Shaders added [[https://github.com/mpv-player/mpv/wiki/User-Scripts#user-shaders][#user-shaders]]
*** [[https://github.com/bloc97/Anime4K/blob/master/GLSL_Instructions.md][Anime4K]]

** Configuration
*** mpv.conf
:PROPERTIES:
:header-args: :tangle mpv.conf
:END:

External Sources of this config:
- https://wiki.archlinux.org/title/mpv    <-- READ WHOLE
- https://github.com/hl2guide/better-mpv-config
- https://raw.githubusercontent.com/classicjazz/mpv-config/master/mpv.conf

#+begin_src conf
vo=gpu         # Uses GPU-accelerated video output by default.
profile=gpu-hq # Can cause performance problems with some GPU drivers and GPUs.
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

border=no              # hides the window title bar

# term-osd-bar=yes     # displays a progress bar on the terminal
cursor-autohide=2000 # autohides the cursor after 1s

# Sets a custom font
osd-font='Iosevka'
# osd-font-size=45
osd-scale=0.5

save-position-on-quit=yes

cache=yes # Uses a large seekable RAM cache even for local input.
# cache-secs=300
# Uses extra large RAM cache (needs cache=yes to make it useful).
demuxer-max-bytes=1800M
demuxer-max-back-bytes=1200M

# Sets the profile restore method to "copy if equal"
profile-restore=copy-equal
#+end_src

**** Motion Interpolation
Enabling those will significantly drop performance on my machine

#+begin_src conf :tangle no
# 3 settings below drop performance and make things laggy
# video-sync=display-resample
# interpolation
# tscale=oversample # smoothmotion
#+end_src

**** Audio
~volume=60~ - volume level to start with

#+begin_src conf
af-add='dynaudnorm=g=5:f=250:r=0.9:p=0.5' # Normalizes audio
af=scaletempo2
#+end_src

**** Color Space
#+begin_src conf
target-trc=auto
gamma-auto
vf=format=colorlevels=full:colormatrix=auto
video-output-levels=full
#+end_src

**** Dithering 
#+begin_src conf
dither-depth=auto
temporal-dither=yes
dither=fruit
#+end_src

**** Debanding 
#+begin_src conf
deband=yes          # enabled by default
deband-iterations=4 # deband steps
deband-threshold=48 # deband strength
deband-range=16     # deband range
deband-grain=48     # dynamic grain: set to "0" if using the static grain shader
#+end_src

**** Subtitles 
#+begin_src conf
blend-subtitles=yes
sub-auto=fuzzy # Enable fuzzy searching:
#+end_src

**** My customs
#+begin_src conf
no-input-builtin-bindings
osd-font-size=45
#+end_src

**** Inactive /mpv.conf/ settings
:PROPERTIES:
:header-args: :tangle no
:END:

Can fix stuttering in some cases, in other cases probably causes it. Try it if
you experience stuttering:

~opengl-early-flush=yes~

***** Anti-Ringing
#+begin_src conf
# scale-antiring=0.7  # luma upscale deringing
# dscale-antiring=0.7 # luma downscale deringing
# cscale-antiring=0.7 # chroma upscale deringing
#+end_src

***** Profiles
#+begin_src conf
# profile=svp

# [svp]
# input-ipc-server=/tmp/mpvsocket     # Receives input from SVP
# hr-seek-framedrop=no                # Fixes audio desync
# resume-playback=no                  # Not compatible with SVP
#+end_src

***** Upscaling & Processing
#+begin_src conf
# glsl-shaders-clr # luma upscaling
# note: any FSRCNNX above FSRCNNX_x2_8-0-4-1 is not worth the additional computional overhead
# glsl-shaders="~/.config/mpv/shaders/FSRCNNX_x2_8-0-4-1.glsl"
# scale=ewa_lanczos # luma downscaling
# note: ssimdownscaler is tuned for mitchell and downscaling=no
# glsl-shaders-append="~/.config/mpv/shaders/SSimDownscaler.glsl"
# dscale=mitchell
# linear-downscaling=no # chroma upscaling and downscaling
# glsl-shaders-append="~/.config/mpv/shaders/KrigBilateral.glsl"
# cscale=mitchell
# sigmoid-upscaling=yes
#+end_src

***** Custom Profiles
#+begin_src conf
[4k60] # 2160p @ 60fps (3840x2160 UHDTV)
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=4k60
profile-cond=((width ==3840 and height ==2160) and p["estimated-vf-fps"]>=31)
# deband=yes # necessary to avoid blue screen with KrigBilateral.glsl
deband=no # turn off debanding because presume wide color gamut
interpolation=no # turn off interpolation because presume 60fps
# UHD videos are already 4K so no luma upscaling is needed
# UHD videos are YUV420 so chroma upscaling is still needed
glsl-shaders-clr
# glsl-shaders="~/.config/mpv/shaders/KrigBilateral.glsl" # enable if your hardware can support it
interpolation=no # no motion interpolation required because 60fps is hardware ceiling
# no deinterlacer required because progressive

[4k30] # 2160p @ 24-30fps (3840x2160 UHDTV)
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=4k30
profile-cond=((width ==3840 and height ==2160) and p["estimated-vf-fps"]<31)
# deband=yes # necessary to avoid blue screen with KrigBilateral.glsl
deband=no # turn off debanding because presume wide color gamut
# UHD videos are already 4K so no luma upscaling is needed
# UHD videos are YUV420 so chroma upscaling is still needed
glsl-shaders-clr
# glsl-shaders="~/.config/mpv/shaders/KrigBilateral.glsl" # enable if your hardware can support it
# apply motion interpolation
# no deinterlacer required because progressive

[full-hd60] # 1080p @ 60fps (progressive ATSC)
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=full-hd60
profile-cond=((width ==1920 and height ==1080) and not p["video-frame-info/interlaced"] and p["estimated-vf-fps"]>=31)
# apply all luma and chroma upscaling and downscaling settings
interpolation=no # no motion interpolation required because 60fps is hardware ceiling
# no deinterlacer required because progressive

[full-hd30] # 1080p @ 24-30fps (NextGen TV/ATSC 3.0, progressive Blu-ray)
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=full-hd30
profile-cond=((width ==1920 and height ==1080) and not p["video-frame-info/interlaced"] and p["estimated-vf-fps"]<31)
# apply all luma and chroma upscaling and downscaling settings
# apply motion interpolation
# no deinterlacer required because progressive

[full-hd-interlaced] # 1080i @ 24-30fps (HDTV, interlaced Blu-rays)
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=full-hd-interlaced
profile-cond=((width ==1920 and height ==1080) and p["video-frame-info/interlaced"] and p["estimated-vf-fps"]<31)
# apply all luma and chroma upscaling and downscaling settings
# apply motion interpolation
vf=bwdif # apply FFMPEG's bwdif deinterlacer

[hd] # 720p @ 60 fps (HDTV, Blu-ray - progressive)
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=hd
profile-cond=(width ==1280 and height ==720)
# apply all luma and chroma upscaling and downscaling settings
interpolation=no # no motion interpolation required because 60fps is hardware ceiling
# no deinterlacer required because progressive

[sdtv-ntsc] # 640x480, 704x480, 720x480 @ 30fps (NTSC DVD - interlaced)
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=sdtv-ntsc
profile-cond=((width ==640 and height ==480) or (width ==704 and height ==480) or (width ==720 and height ==480))
# apply all luma and chroma upscaling and downscaling settings
# apply motion interpolation
vf=bwdif # apply FFMPEG's bwdif deinterlacer

[sdtv-pal] # 352x576, 480x576, 544x576, 720x576 @ 30fps (PAL broadcast or DVD - interlaced)
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=sdtv-pal
profile-cond=((width ==352 and height ==576) or (width ==480 and height ==576) or (width ==544 and height ==576) or (width ==720 and height ==576))
# apply all luma and chroma upscaling and downscaling settings
# apply motion interpolation
vf=bwdif # apply FFMPEG's bwdif deinterlacer

[default]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
#+end_src

***** File Type Profiles
#+begin_src conf
# GIF Files
[extension.gif]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=gif
cache=no
no-pause
loop-file=yes
# WebM Files
[extension.webm]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=webm
no-pause
loop-file=yes
#+end_src
***** Protocol Specific Configuration
#+begin_src conf
[protocol.http]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=http
hls-bitrate=max # use max quality for HLS streams
cache=yes
no-cache-pause # don't pause when the cache runs low

[protocol.https]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=https
profile=protocol.http

[protocol.ytdl]
profile-restore=copy-equal # Sets the profile restore method to "copy if equal"
profile-desc=ytdl
profile=protocol.http
#+end_src

*** input.conf
:PROPERTIES:
:header-args: :tangle input.conf
:END:

[[https://github.com/mpv-player/mpv/blob/master/etc/input.conf][default keybindings]]

Use SHARP to assign the # key.

List of commands and further details: DOCS/man/input.rst
List of special keys: --input-keylist
Keybindings testing mode: mpv --input-test --force-window --idle

Use 'ignore' to unbind a key fully (e.g. 'ctrl+a ignore').

Strings need to be quoted and escaped:
  KEY show-text "This is a single backslash: \\ and a quote: \" !"

The default keybindings are hardcoded into the mpv binary.
You can disable them completely with: --no-input-default-bindings

Developer note:
On compilation, this file is baked into the mpv binary, and all lines are
uncommented (unless '#' is followed by a space) - thus this file defines the
default key bindings.

If this is enabled, treat all the following bindings as default:
#+begin_src conf
# THIS FILE IS BEING TANGLES FROM README

default-bindings start
#+end_src

*Note:* All key bindings below that are bound to ~_~ are defined as leader ones in
my leader script.

**** Playback
#+begin_src conf
# Seek units are in seconds, but note that these are limited by keyframes
l seek  5                          # seek 5 seconds forward
h seek -5                          # seek 5 seconds backward
# Do smaller, always exact (non-keyframe-limited), seeks with shift.
# Don't show them on the OSD (no-osd).
L no-osd seek  10 exact       # seek exactly 10 seconds forward
H no-osd seek -10 exact       # seek exactly 10 seconds backward

Ctrl+=     add video-zoom   0.1 # zoom in
Ctrl+-     add video-zoom  -0.1 # zoom out
# reset zoom and pan settings
Ctrl+0 set video-zoom 0 ; set video-pan-x 0 ; set video-pan-y 0

[ multiply speed 1/1.1 # decrease the playback speed
] multiply speed 1.1   # increase the playback speed
> multiply speed 0.5   # halve the playback speed
< multiply speed 2.0   # double the playback speed
0 set speed 1.0        # reset the speed to normal

SPACE cycle pause       # toggle pause/playback mode
PLAY cycle pause        # toggle pause/playback mode
PAUSE cycle pause       # toggle pause/playback mode
PLAYPAUSE cycle pause   # toggle pause/playback mode
PLAYONLY set pause no   # unpause
PAUSEONLY set pause yes # pause
#+end_src
**** Subtitles
Bind those if ya'll ever need 'em:
Shift+g add sub-scale +0.1             # increase the subtitle font size
Shift+f add sub-scale -0.1             # decrease the subtitle font size
Ctrl+Shift+LEFT sub-step -1            # change subtitle timing such that the previous subtitle is displayed
Ctrl+Shift+RIGHT sub-step 1            # change subtitle timing such that the next subtitle is displayed

**** Audio
#+begin_src conf
j add volume -2
k add volume 2
m cycle mute                           # toggle mute
#+end_src

**** Shaders
#+NAME: Anime4K
#+begin_src conf
CTRL+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A (Fast)"
CTRL+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode B (Fast)"
CTRL+3 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode C (Fast)"
CTRL+4 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_Restore_CNN_S.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A+A (Fast)"
CTRL+5 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_S.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode B+B (Fast)"
CTRL+6 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_S.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode C+A (Fast)"
CTRL+0 no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"
#+end_src

**** Misc
#+begin_src conf
# Quitting
# q quit
Q quit-watch-later # exit and remember the playback position
# q {encode} quit 4
ESC set fullscreen no                  # leave fullscreen
ESC {encode} quit 4

? show-progress                        # show playback progress
# toggle displaying information and statistics
i script-binding stats/display-stats-toggle 
` script-binding console/enable        # open the console
Ctrl+F cycle fullscreen                     # toggle fullscreen

Alt+v cycle video                          # switch video track
# cycle the video aspect ratio ("-1" is the container aspect)
Alt+Ctrl+v cycle-values video-aspect-override "16:9" "4:3" "2.35:1" "-1"

# take a screenshot of the video in its original resolution without subtitles
Ctrl+S screenshot video
#+end_src

**** Unknown purpose
#+begin_src conf :tangle no
#w add panscan -0.1                     # decrease panscan
#W add panscan +0.1                     # shrink black bars by cropping the video
#e add panscan +0.1                     # shrink black bars by cropping the video

#E cycle edition                        # switch edition
#ctrl+h cycle-values hwdec "auto" "no"  # toggle hardware decoding

#d cycle deinterlace                    # toggle the deinterlacing filter
#+end_src

** To do list [0/5]
*** TODO [[https://github.com/sebaro/ViewTube][viewtube]] for my main pc?
*** TODO [[https://github.com/stax76/mpv.net][mpv.net]] for windows ?
*** HOLD mpv as a music player
[[https://wiki.archlinux.org/title/mpv][this]] article also has a section called /Improving mpv as a music player with Lua
scripts/ which might b sometime useful again for my main pc
*** IDEA [[https://github.com/zenyd/mpv-scripts][copy-paste-url]]
*** IDEA Anime
https://github.com/ehoneyse/mpv-open-anilist-page
